---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/flux-kustomization.yaml
  - cloudnative-pg/flux-kustomization.yaml
  - longhorn/flux-kustomization.yaml
  - redis-operator/flux-kustomization.yaml
  - seaweedfs-operator/flux-kustomization.yaml
  - traefik/flux-kustomization.yaml
