---
nebula_config_static_host_map:
  10.44.4.10: [85.208.85.159:4646] # Silky
  10.44.8.10: [57.128.251.65:4646] # Mala

nebula_config_lighthouse_list: [10.44.4.10]
nebula_config_relay_list: [10.44.4.10]
