---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-config
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/longhorn/config/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  dependsOn:
    - name: longhorn-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
