---
- name: Get latest Nebula version
  when: nebula_download_version == "latest"
  block:
    - name: Fetch latest Nebula release on GitHub
      register: nebula_download_github_release
      community.general.github_release:
        user: "{{ nebula_download_github_user }}"
        repo: "{{ nebula_download_github_repository }}"
        token: "{{ lookup('ansible.builtin.env', 'ANSIBLE_GITHUB_API_TOKEN') }}"
        action: latest_release

    - name: Set Nebula version fact
      ansible.builtin.set_fact:
        nebula_download_version: "{{ nebula_download_github_release.tag | ansible.builtin.regex_replace('^v', '') }}"

- name: Link current version directory
  block:
    - name: Create version directory
      ansible.builtin.file:
        path: "{{ (nebula_download_local_dir, nebula_download_version) | ansible.builtin.path_join }}"
        mode: "0755"
        state: directory

    - name: Link current version directory
      ansible.builtin.file:
        src: "{{ (nebula_download_local_dir, nebula_download_version) | ansible.builtin.path_join }}"
        dest: "{{ nebula_download_current_local_dir_link }}"
        state: link

- name: Download Nebula binaries
  block:
    - name: Check if the Nebula archives already downloaded
      loop: "{{ nebula_download_architecture_map | ansible.builtin.dict2items }}"
      register: nebula_download_files
      loop_control:
        label: "{{ nebula_download_architecture.key }}"
        loop_var: nebula_download_architecture
      ansible.builtin.stat:
        path: "{{ (nebula_download_current_local_dir_link, nebula_download_architecture.key) | ansible.builtin.path_join }}"

    - name: Download Nebula archives
      when:
        - not nebula_download_files.results[ansible_loop.index0].stat.exists
        - nebula_download_architecture.key in common_unique_architectures
      loop: "{{ nebula_download_architecture_map | ansible.builtin.dict2items }}"
      loop_control:
        label: "{{ nebula_download_architecture.key }}"
        loop_var: nebula_download_architecture
        extended: true
      ansible.builtin.get_url:
        url: "{{ nebula_download_url }}"
        dest: "{{ (nebula_download_current_local_dir_link, nebula_download_architecture.key) | ansible.builtin.path_join }}"
        mode: "0644"
