$ANSIBLE_VAULT;1.1;AES256
39393666326338656361616633396165316561636332663430303736386432303364363934646662
3936303638666233356230646131323166616565383434650a643639643631333736303035353937
30343032373262326431646261303062313564383462316632343334336465373361643462363934
3931626261373864330a306265363065636238386462363366353933636661353032656665303633
64663466343565373764366630316131363964363833653862653364643838376530313831313233
61333261626330396230376364383130616565353434663862353464643266373762346532646333
63303238306261633161383964333032643136653936616632306231386666653362303630626430
30306431663530353937323162353838323431366335326665623539366635613739633063333563
33313830346536346537323162343436323166646633353539663066376330313537393162333332
31653065303136396431393839326237626335623164643531613164653437323233366335393337
303866653532646361643837646437336261
