$ANSIBLE_VAULT;1.1;AES256
66323830616230376232643038393036626437313131363739356337333335316436663032363031
6533336330333031353235656266346239386632353335630a326334336437323539616363656336
35353762313937393562643536313761383632323439343335316339616637623463323665343536
6364343361613235640a653730623035303033323234376636666461373730346239653531336238
61316366336237623732356635663330636139356135663462353938636333316162653365316334
30346261363865303132333632366133643465336665373132316239326434623137333262356239
33663932316565336139643837666565353538333836356138616538616166363263643131626237
66316361323562353664353533393239373133363434633761393566646437666236373466346666
39343735353539656163323839666362626364656661363865303061653631623261613961373662
39636463653939343239373230656466613235343738626532333263323464663538386664626236
313862363039333832313431306137636535
