apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-seaweedfs-redis-secret
  namespace: gotosocial
type: Opaque
stringData:
  redis_password: ENC[AES256_GCM,data:ijKQZfQGQG88LTbjhP9ZEym7FOLqdYxvc7hR8QwDHM0=,iv:P5Cvri3NQsqNZsFqJ+ei9Wd75JvdWaE3hTLEcBTXtBo=,tag:EnzKwMGxD5n6k0nAH+5b4w==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1FWeXdZbzZrS0huYWdF
        c2JTa3BmM1BWeTBWcjZNczFXc3A0ZVlLRkQwCnVoTlB1THlEYTBNVXFkUFNjYk5Z
        YVJPRGh2TVgvSThDSndWdG1kU2hjSk0KLS0tIEkyY2Z3Z1dWN3hYaEJ2R3pUSmNF
        MldoUmZOazkwRE1jTThDT3B4Z0dZZmcKx2d0RkhaE0u9xqpDEpcievHSU3JNrLry
        SeH1yE0bMafkuTbqXKKzBnzi+iGYf+1d+hlPh3p+H5ne4i7KRzoq3A==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TFVyTlJMYWh3T1lWbTNt
        enB3dm9JRi9FVndaRXIyVUlHZkozU3gzbkhFCm9MNXRQUE9lQ2g4TUprMjZ6N0RH
        TEhWK1lJb3hZUTBSekhNblRTdjFERVEKLS0tIDVvVk42bzdZdDdGR2xHYW5Xemlv
        KythWmdGSmYxT0FyZGh3Ykt6c2ZmRTAKd20fhYTzIqWAIYHMbNuGlBfBUchbJ49i
        Qkl9wtOsBFzkRPZrHVCap8pQ4xO2wYqfZJ8pR6VRHwhpRj1Vy2ptCQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T19:19:47Z"
  mac: ENC[AES256_GCM,data:oOTu7orGUHyt72kGAa4lVrjOB2AuWuJn7Yn04bbJRCJtIwHMtbjGAuLveyG4yVs4ixrJT8D9jNvErQF+h+fj3dUtLyXft+zNzJXlLve3cSJ4nggNCgSo+9m+wyBvpJJCWXEZIFINlKQrdzHc321H6IGJOSmlbYpCuBGNTAc6k14=,iv:ET0q7afc7UtvmEwPSsxafrcy2qEDeC9iuuzh7E9DZkA=,tag:K4x7sEKm7fvTAmKYRUTfcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
