apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-seaweedfs-secret
  namespace: gotosocial
type: Opaque
stringData:
  seaweedfs_s3_config: ENC[AES256_GCM,data:MGGuG0+O+Ylfw/eW3Rc540E1D/3Ani+grJpZjHwNr2nsC6+pYZIIjFkKorl6xy/kuQLrsv5dfKNmva4RGLMvzfm8qHzNvVQsr+RjOnFv5YV2vrHrZAz8Is8R94zz6m6lt6dk6xtTUvk48Ttd1NVD86A0VoLjWJqv42iDw5gk98BjHG0XFIsiPksx1hUn4IYY8ZOX/qKxMnbtmZSiSRyoS1HsaW1j76I1u861/VOCDCloIquFZbrAlnwrkrU7yTbeNig3pOy9TEB1+4fYfSgeV9iHK+vpYEC2nYW3Rwlf6AG79uX37q0oVi0yERTWrhDxqnZTH30bHkvBWq7Aq/5aui/zpYhEBGx5NcKkSlhc9cFbXM4dARcwOes3ccG3M6wnLllfyZAKRSuGVZ9kw/AI8pU8ZDGZcA==,iv:6z06ZDFhsZTBSX5vs0DXhuWxDcjYyWthANjbfMaTUs4=,tag:uL87malYmfCz8/f+2ISnQg==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYlVFbUd1cXFqRmVYV2pQ
        VFAyZUthbHZvZnRVUmhyeTNWc1l4V1VjaGdVCkFVd0Jyc1U0VmVtWXd4L3B0YW5K
        Y0VuUjZaTm5yeXIwSm1vVlpKQ2FIb3cKLS0tIG9ROG1ZenczTVRub00welI4cFRj
        V0QxRzhEdm9yL2xWUGhBWlpCaXo5OUUKx4ZYABcTM3ZDKdUeYui7JBqppBuroTmZ
        jfM6iVtB1816h2z1k2CBEM+EQqRdQUdmhOra5HXfR8JQcGcxDSrnlQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ1UwZS9FTUlZOXV5TWha
        ZzVobWxkK0JTZk5oRWJuUmdTaEZpUG1ySkZZCjlmdkdKckFwUGFWUWxYK3FYR1lv
        dXRTbG43WUlGME42RkdZcXlTT2tnOXMKLS0tIGx2MktTM3V0SUNHRXpMR3Zna2Vn
        NHMxa3VJYTF5TXN3SUxybUxCeVg4QVEKNrqK21N7VZ73/+5tgQCYD5YJm11AGkdI
        fToq9ncJ27OLV87frBe5gUA5wE92nfjqdjzHI8etuqZ/KSwIwZVJGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T19:19:29Z"
  mac: ENC[AES256_GCM,data:VZSdCiwPLx/lI5lRDW3oBQkvmq+NxUfEo7koVwnaPpXrINkfx/s2IB9jOvk4/Ou43f+q8B0ld99GnBGCcl9j65b/E7J+Vj5y3NCw3BuEckmN2trbuVQY9QFG/35U5/HFuI295YlC+lSaEfKJRv1bxr1h/pX9g2bk3s+I02rMeO8=,iv:/MNvdyTGOYkivY/i4rdR7OBE1gH0EZbacUOXeIoYLqI=,tag:naj7F4kq0zo271dBUmf74w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
