apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-secret
  namespace: gotosocial
type: Opaque
stringData:
  s3_access_key: ENC[AES256_GCM,data:/Dn+HjHtTxWJgO9Y9xbGCw==,iv:peYijElivNKIybRXZryJlmy1lZzk8UlFqn4hLMCdePM=,tag:I68ccVqDFwGs3aPDk+FD5w==,type:str]
  s3_secret_key: ENC[AES256_GCM,data:oyfHxyA6zKl50ETyflqhZhWcnmRxbYYHAl9Hy3jXKV9Eiwo2Df/A/+VT5D9DZx3J,iv:+c37o9D8mAnCbhQOia4x//GCNg40ar6GqAututatWvc=,tag:Y7QMDXU+uj59vvAcIpA+ng==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VkQ0N080cFl4NkhFOG0x
        S3VPNVNGUXUvREZ0eEo5UDRwQlJTVk53RER3Cm43VFdQVzlHVVgweU1GTzk5RHNI
        R2w5Q0FDWW1KRGFHVFBPbk53bGVLWE0KLS0tIFRDQngrQzZzSkkvdVpxSnc5dXlP
        NXAxUzRYMTFpcUhGNFdwSnFKRFhFQ1EK8lF7danF90aYGeGP5XTReuMU4E/jlDU3
        dQyhPU7Yaoh7KAjUJjWqlTMBVFDFNwTSIp2aR0WNLRrFftTgqjGoAQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZXFhK3gvbkNwMEZUb0JN
        R000YUUrVmRKK3dIb3FyYUN2NHVNdENUTDFjCnMvYkdqSUQ0M2RZZlNtSjc1akFq
        Q2dmRTQ1VElZaHRrQmc5amtDeGdzUzAKLS0tIGVsRjN0T0xRZ3NLaXo4WDNSa1dF
        d0xKUm1CWWpwTjc2NWI4RUVrQ1hhS2sKmEMFlgO1I7rGbIemyikEhPrwO/WGevwV
        +WAIELAE4+y1qk+13dPMF/v/T4grFS47MiBMP5e/RkTozkk1QuOmbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-05T19:19:54Z"
  mac: ENC[AES256_GCM,data:90GlT+gdYZxNc2nkOh30frAGdWpA2B0H6Ei5Yie3ZVVIkmJbClwDV+3zqIga0d/Sb9cScQHLusJ10S6d0zQe+xbhmC7gTBzE2nP4JP2RbayGoCGUgmE39glUXBm/YdWf0xK534Ecdj1ENZLYEf3Wk1TYbreRScMG940wd3DmcUk=,iv:VJcR0OEtyanWT6LDvNjCzry21JKFDv6uTNlK0JW1oc4=,tag:LGQ7+RfpsC9pgVPk0AsQgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
