---
# Local path for storing Nebula cache.
nebula_cache_local_dir: "{{ (common_cache_local_dir, 'nebula') | ansible.builtin.path_join }}"

# Local path for storing Nebula cache.
nebula_artifact_local_dir: "{{ (common_artifact_local_dir, 'nebula') | ansible.builtin.path_join }}"
