---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seaweedfs-operator-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/base/controllers/seaweedfs-operator/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: seaweedfs-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cert-manager-controller
