---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: redis-operator-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/redis-operator/controller
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: ot-operators
  sourceRef:
    kind: GitRepository
    name: flux-system
