---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/cnpg/controller/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: cnpg-system
  sourceRef:
    kind: GitRepository
    name: flux-system
