---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/secret.yaml
  - ../../../../../base/controllers/external-dns
patches:
  - path: patches/flux-kustomization.yaml
