---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/apps.yaml
  - resources/flux-instance.yaml
  - resources/flux-operator.yaml
  - resources/infrastructure.yaml
  - resources/namespaces.yaml
  - resources/repositories.yaml
