---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repositories
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/repositories
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
