---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gate-lite
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: gate
          image: gate
          ports:
            - name: minecraft
              containerPort: 25565
          volumeMounts:
            - name: config
              subPath: config.yml
              mountPath: /config.yml
      volumes:
        - name: config
          configMap:
            name: gate-lite-config
