---
- name: Configure kernel
  loop: "{{ proxmox_nat_sysctl | ansible.builtin.dict2items }}"
  loop_control:
    label: "{{ item.key }}={{ item.value }}"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ proxmox_nat_sysctl_file }}"
