---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: woodpecker
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/base/woodpecker/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: woodpecker
  sourceRef:
    kind: GitRepository
    name: flux-system
