$ANSIBLE_VAULT;1.1;AES256
63323161316463303438386462653332336233646635623730613962396162306166333366633762
6266643964303762666161613339663034306461666563640a323433653663346163383163316634
38363233396536633564643661326137353933613238393062313365656336636266343364353038
6335336466306165350a316265393162663531616162316530376233306238303835343734386437
32666330626461366137383234363061386534363236383136356639333263343730363261303232
38343936613962633531636237666133366536616531333833316362373362323135623733636636
38653238643366623361633165626664613166613465633831333362323738623861376263303461
65353435376361346236653230323965623531386362396638616664376439373839323838656266
35306465636437616664626261313761343331643434636430653733636661633732613961396162
39326537363439316238643032623332623430376662346263623933616161333663646234653039
64323862633735336431343033356463303434336363396632656462386465333138656635336264
33353837303736306335626430343131313337393832663936383634643461386466633336613465
39383365323735353461333065666230343261613366653337393538613263653363
