---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: woodpecker-server
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/production/woodpecker/server
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: woodpecker
  sourceRef:
    kind: GitRepository
    name: flux-system
