---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gotosocial-db
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  storage:
    size: 5Gi
    storageClass: longhorn-local
  bootstrap:
    initdb:
      database: gotosocial
      owner: gotosocial
