---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: gotosocial-seaweedfs-redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: gotosocial-seaweedfs-redis-secret
      key: redis_password
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn-local
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 2Gi
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
