---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/controllers/longhorn
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: longhorn-system
  sourceRef:
    kind: GitRepository
    name: flux-system
