---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/cloudnative-pg.yaml
  - resources/jetstack.yaml
  - resources/longhorn.yaml
  - resources/opstree.yaml
  - resources/seaweedfs-operator.yaml
  - resources/traefik.yaml
