---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/cloudnative-pg.yaml
  - resources/external-dns.yaml
  - resources/jetstack.yaml
  - resources/longhorn.yaml
  - resources/opstree.yaml
  - resources/seaweedfs.yaml
    - resources/traefik.yaml
