---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: backup-store
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/backups/store
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: backups
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: longhorn-controller
    - name: longhorn-config
    - name: redis-operator-controller
