---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gotosocial
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/base/gotosocial/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: gotosocial
  sourceRef:
    kind: GitRepository
    name: flux-system
