---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: woodpecker-db
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: longhorn-local
  bootstrap:
    initdb:
      database: woodpecker
      owner: woodpecker
