---
k3s_server_config:
  disable: "{{ k3s_server_config_disable }}"

  node-ip: 10.44.0.10
  node-external-ip: 192.168.1.10
  advertise-address: 10.44.0.10

  tls-san:
    - 192.168.1.10
    - lestat.kasefuchs.net

  node-label:
    - backup-store=true

  flannel-iface: nebula0
