---
- name: Render K3s server template
  vars:
    k3s_config: "{{ k3s_server_config }}"
  notify:
    - Enable K3s server service
    - Restart K3s server service
  ansible.builtin.template:
    src: config.yaml.j2
    dest: "{{ k3s_config_file }}"
    mode: "0644"
    owner: root
    group: root
