---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/seaweedfs-redis-secret.yaml
  - resources/seaweedfs-secret.yaml
  - resources/secret.yaml
  - ../../../../base/gotosocial
patches:
  - path: patches/flux-kustomization.yaml
