---
all:
  hosts:
    fawzi: { ansible_host: 192.168.1.10 }
    esme: { ansible_host: 192.168.1.20 }
    coral: { ansible_host: 176.108.245.168 }

proxmox_ve:
  hosts:
    fawzi:

nebula:
  hosts:
    fawzi:
    coral:

nebula_lighthouse:
  hosts:
    coral:

nebula_node:
  hosts:
    fawzi:

k3s:
  hosts:
    coral:
    esme:

k3s_server:
  hosts:
    esme:

k3s_agent:
  hosts:
    coral:
