---
all:
  hosts:
    lestat: { ansible_host: 192.168.1.10 }
    silky: { ansible_host: 85.208.85.159 }
    mala: { ansible_host: 57.128.251.65 }

nebula:
  hosts:
    lestat:
    silky:
    mala:

nebula_lighthouse:
  hosts:
    silky:

nebula_relay:
  hosts:
    silky:

k3s:
  hosts:
    lestat:
    silky:

k3s_server:
  hosts:
    lestat:

k3s_agent:
  hosts:
    silky:
