---
# CN for the CA.
nebula_cert_ca_cn: Nebula CA

# Duration of CA validity.
nebula_cert_ca_duration: 87600h

# CN for the host certificate.
nebula_cert_host_cn: "{{ inventory_hostname }}"

# List of subnet ranges assigned to the host certificate.
nebula_cert_host_subnets: []
