---
# Nebula configuration.
nebula_config:
  firewall: "{{ nebula_config_firewall }}"
  lighthouse: "{{ nebula_config_lighthouse }}"
  listen: "{{ nebula_config_listen }}"
  pki: "{{ nebula_config_pki }}"
  punchy: "{{ nebula_config_punchy }}"
  relay: "{{ nebula_config_relay }}"
  static_host_map: "{{ nebula_config_static_host_map }}"
  tun: "{{ nebula_config_tun }}"

# Host and port where the Nebula service listens for incoming traffic.
nebula_config_listen:
  host: 0.0.0.0
  port: 4646

# Nebula lighthouse configuration.
nebula_config_lighthouse:
  am_lighthouse: false
  hosts: "{{ nebula_config_lighthouse_list }}"

# Hosts is a list of lighthouse hosts this node should report to and query from.
nebula_config_lighthouse_list: []

# Name of the TUN interface created by Nebula.
nebula_config_tun:
  dev: nebula0

# Firewall actions and rules for Nebula traffic.
nebula_config_firewall:
  inbound_action: drop
  outbound_action: drop
  inbound:
    - { host: any, port: any, proto: any }
  outbound:
    - { host: any, port: any, proto: any }

# Config for UDP hole punching support.
nebula_config_punchy:
  punch: false
  respond: false

# Settings for enabling or using relay nodes in Nebula.
nebula_config_relay:
  relays: "{{ nebula_config_relay_list }}"
  am_relay: false
  use_relays: true

# Relays are a list of Nebula IP's that peers can use to relay packets to me.
nebula_config_relay_list: []

# The static host map defines a set of hosts with fixed IP addresses.
nebula_config_static_host_map: {}
