apiVersion: v1
kind: Secret
metadata:
  name: x-ui-secret
  namespace: x-ui
  labels:
    reconcile.fluxcd.io/watch: Enabled
type: Opaque
stringData:
  vless_route_match: ENC[AES256_GCM,data:6Nft4rEZKcbnkzWuL+G2i9m9qGX37J8=,iv:Fo5hV/R74xATHv+3gt3PjWhi4X6FHwTMHCRFmyEnh8k=,tag:Q/et6c7TXzeCdnRq+7scDQ==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQVFVNFoxVG5HR2tIc0pH
        ZWduVm5mU0t1elhpZlJKOEZXTm1HcTR1YjFNCnZnRyt2Q1lKSVM0Z282QTNWdFRS
        YmpzWnFEa2t4YUYySVMxL28wQ1lVY1kKLS0tIGt1ZnpVQThqMWtCVThEZ25MMTdO
        bHNXQjhOLzAzejIxNjVQVm5yOThaVFEK3GuatkF7hVj/Jct6YljRK4mEBu9WgAdm
        XqQCS1lMm7UqWdeOjBtXpeU/b1WbUHRWJpKBvrtaJvdfEadB1zVkXQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRVIvUk1aLzdZUWRoOC9C
        a2dFRG42ODAxT3MwblNnM0dQQ2FnbFNDeVZVCjlVY1NJQlJMOGxBVkZLdUtQcUNj
        dkNTUmlnNUtMOHczQTFKUU5LUzIwdk0KLS0tIE95SWNSVkNWZkU2Szhhb1B5WnhH
        Vm5KN21ZY0JDeGdlVHFtdnpXYitGMlkKyRJ/2DX+sdCbmqvASgza8MRDKwz6r4ht
        yGVagPhcG6bkc4nPyCteBNv4ucEa0JKQ2b6vO1hbBfd6SGpEHRGypQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T20:47:02Z"
  mac: ENC[AES256_GCM,data:IujAzyu+7ux6KcXl8SHBfzVzA8LzMSUN6BqMVbTg8euqeuZuOMDa7LGSA5QOeUM5s1sCcOQL580T76droUF3qK+ok+E1yZHmhA2WPsqMz4732vCJHYMk+9kB1XDIF+YUa0a/dptw3t8yZnBMMFbfIhn+MIyPTSwW6GS3jLyZDwQ=,iv:Vfl9TTR1JsWZS/l8fVOILS3ExXB0aWbZfdtk0pINn9U=,tag:hMafdOGanZMojXWphYiCEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
