---
- name: Create K3s directories
  loop:
    - "{{ k3s_install_dir }}"
    - "{{ k3s_install_config_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
    owner: root
    group: root

- name: Copy K3s binary
  ansible.builtin.copy:
    src: "{{ k3s_download_binary_local_file }}"
    dest: "{{ k3s_install_binary }}"
    mode: "0755"
    owner: root
    group: root
