apiVersion: v1
kind: Secret
metadata:
    name: store-secret
type: Opaque
stringData:
    redis_password: ENC[AES256_GCM,data:AdWL4xAi4Hard/vlERIBVWsB3i8ZHDW/a7ZP21U2oKkV+Kmy,iv:gjlzUrSoR8hu7iasOChsFZVmdMYeEkkINmgFZRjg1QQ=,tag:JL5iKzdlXsstZEXXhhi/EQ==,type:str]
    seaweedfs_s3_config: ENC[AES256_GCM,data:iZLRvZ/NxAWT4ubTyeQqo5mU,iv:Qq5/mJ7Eo75CadLIDriiZUujpHxL9nstaEM5BKXvJnQ=,tag:a3gAfYKlP1V+n5nA9g9zcw==,type:str]
sops:
    age:
        - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTlJNZ0JnZUkwV2Rtak1H
            ZmZEV2VrQ3dkSWkwWXQvZE5reWVVZ240RGlzClZ3U1Myc0lDS2xwM1kyY250VGQx
            c1hRZjVUSFRGK2g4ckNvL3F4ekNrNm8KLS0tIEJtaXNIejM4b3gxckxsM0lrcHRT
            bUJPUWpTejRsRmxySUI0dkFmVFRBU2sKNfE94G1q1VsdryUTy1hDoBQfSxND047G
            KbNW8qHtyDdCnzzhhvF+2curSIheT1MQ0dTguffl05h6E02OQcr5fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU0s0SDdvWHRPNWxkaTRO
            c05CL3RTMnBBamd5YS9iYXN6dHFaZFZ5ODB3CnNVdi9SSllpeTRpT2RSdWM5VUFW
            OFB6WnpyT2RvUUIyOVlZeC9GM1lxSjQKLS0tIGpURmNPaHVITEtncDNjMFVKWkxE
            SzhabXJEbWdNNlF1enRDOUZtOFdVM0UKkpGzbNRJDnVIOlbHXspKYwShNtbbQ5za
            LKPnu2tgooduyKE3V8IKyx5NY84/qrPWuC1I91GUhvcZVicbyLmZnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T10:53:05Z"
    mac: ENC[AES256_GCM,data:Zf4bTVQ6JBn76O0aWO7AR0bT4wnZeT3PntGo1yAIsNiEY3opY3f8WnW6ZvdI3cSc19KDoT4zCZHZtWRPUb1xejhSLat/Tx4SRAPZpRNEuUjE2Wvec66iENVZg7gKqWp1Hmy7TrNulCwSZPe4dnyx1VB9CiYTcAcyYeh06105G9s=,iv:8+YqU36Zq90ziX8eL/UYBZ9KNhwypVaEn9vdtfx4nK8=,tag:fYLq5P92loibmZl7abxysQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
