---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/base/controllers/traefik/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: traefik
  sourceRef:
    kind: GitRepository
    name: flux-system
