---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config-overlay
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/overlays/production/configs/cert-manager/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
