apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: external-dns
type: Opaque
stringData:
  desec_token: ENC[AES256_GCM,data:AH6UN4TtmsQz+eG+HtgOX2ApS7Ml5qkN0ghqrA==,iv:vv93FRRIAr1mJKCqOmyVT94OJS1SzZIhWukmv54q2Xc=,tag:eJvKqUG+84gF03HtGGiHtw==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U3pyMEdpSHB3MitMemxx
        Sk8zM3BFN1dDbUN4MEpBWGxQNjRxMG9sRWdVCmhFZk5MbUtqWkhQaTl3Mm9BSC9h
        eVVxMURHQTRoaVJodzJEc3lrZEprekEKLS0tIDhZMHJaRlZ4amJnN29NYVo0L3ds
        RUNxaFk5aDhVTHQ5MXMydEJhMHlFUjAKxij65Z01WktVUWYPD7cOaitsd75VcJ9r
        A3ZRCzM6/yIfkuimn71bNWl3i06XAhDFlG8ozxdoRM37b/EWdFA2hQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcktPVldKZGVQek1XaytJ
        M2pBYzJOMmJaSlNiZ0F3ODJvRmo0MFlpczM4CmJkL1lLUEVaamEwelpVU3R3Qy9s
        bkJ4UDJ1TWlFajFYaDRKNnNBOTF6b2sKLS0tIDVvcnlYVUVSY3I4WkllTFBTYjVK
        N1hLYXA4MThYZGp2VzJMWXlBSHRZWXMKc/1h5THquvwPVDi8D+LgjVPqyqHe5CBQ
        IS4OS3q957+N4YhXun4sccMrh7IKodnHg4AZofPM2euavr2AgT0lsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-04T20:48:04Z"
  mac: ENC[AES256_GCM,data:Krqb6md9voVlaUqFlc3ZwmNnZZrHRDKO07vPSXBclwUHAHxcFcMSP6MWqaCkEtQ3zYhaWBozTNsgAFWv/WEfd9YX/B6ILBXYjimIdnuOTSLGWeVk2WEN+weYETGbUxYk2615+Fl5UGNGsk3ahRtCfPvWS8AagzudyD3q9Eq9QFs=,iv:ORPQ+dVsHPv+/UzaT13e+AGcv11tb/Y5Uj5WDzIbSrY=,tag:PBEIcFm652/0MrGpY7c8Hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
