apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
  namespace: external-dns
type: Opaque
stringData:
  cloudflare_api_token: ENC[AES256_GCM,data:qqUtZND4bb1waqZEVS2c6vQw/f4xgkCdm3V2MbcocR7RLNV8s4ROWg==,iv:OasXLkTldPCj/Y7iQGm+11QhYciifl5dQzvfH4oWExE=,tag:RTHTGFfNKR9Vs/FwneVlrg==,type:str]
sops:
  age:
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4U3pyMEdpSHB3MitMemxx
        Sk8zM3BFN1dDbUN4MEpBWGxQNjRxMG9sRWdVCmhFZk5MbUtqWkhQaTl3Mm9BSC9h
        eVVxMURHQTRoaVJodzJEc3lrZEprekEKLS0tIDhZMHJaRlZ4amJnN29NYVo0L3ds
        RUNxaFk5aDhVTHQ5MXMydEJhMHlFUjAKxij65Z01WktVUWYPD7cOaitsd75VcJ9r
        A3ZRCzM6/yIfkuimn71bNWl3i06XAhDFlG8ozxdoRM37b/EWdFA2hQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcktPVldKZGVQek1XaytJ
        M2pBYzJOMmJaSlNiZ0F3ODJvRmo0MFlpczM4CmJkL1lLUEVaamEwelpVU3R3Qy9s
        bkJ4UDJ1TWlFajFYaDRKNnNBOTF6b2sKLS0tIDVvcnlYVUVSY3I4WkllTFBTYjVK
        N1hLYXA4MThYZGp2VzJMWXlBSHRZWXMKc/1h5THquvwPVDi8D+LgjVPqyqHe5CBQ
        IS4OS3q957+N4YhXun4sccMrh7IKodnHg4AZofPM2euavr2AgT0lsA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-06T08:33:03Z"
  mac: ENC[AES256_GCM,data:Rd85KzqykzFer2oH8ku8VX5PXWoPeHUvpJjdQDK5OL4O9Zz7Y/AXzubUzxb5QLYkeKDQzHws9iZUPFEWeSiXc/HVulCQCzGcHQ/RJ4GHkvvWIkmR3xUQi3D/fpajQADqeFboyvhzOnTlxiI7AsJ2TTcLhDi3gmAA756HnFjMAVc=,iv:yGu8qBxqWgQQX3xfqQ/Gb5tKTxu4AF87lNbZV1oex5Q=,tag:cgvYP8jID8JgjftyaY5sog==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
