---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gate-lite
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/production/games/gate-lite/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: games
  sourceRef:
    kind: GitRepository
    name: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
