---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  interval: 1h
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  chart:
    spec:
      chart: redis-operator
      version: 0.23.x
      interval: 2h
      sourceRef:
        kind: HelmRepository
        name: opstree
        namespace: flux-system
  values:
    featureGates:
      GenerateConfigInInitContainer: true
