---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: gate-lite
    includeSelectors: true
images:
  - name: gate
    newName: ghcr.io/minekube/gate
    newTag: latest
resources:
  - resources/deployment.yaml
  - resources/service.yaml
configMapGenerator:
  - name: gate-lite-config
    files:
      - config/config.yml
