---
- name: Get latest Vault version
  when: vault_download_version == "latest"
  block:
    - name: Fetch latest Vault release on GitHub
      register: vault_download_github_release
      community.general.github_release:
        user: "{{ vault_download_github_user }}"
        repo: "{{ vault_download_github_repository }}"
        token: "{{ lookup('ansible.builtin.env', 'ANSIBLE_GITHUB_API_TOKEN') }}"
        action: latest_release

    - name: Set Vault version fact
      ansible.builtin.set_fact:
        vault_download_version: "{{ vault_download_github_release.tag | ansible.builtin.regex_replace('^v', '') }}"

- name: Link current version directory
  block:
    - name: Create version directory
      ansible.builtin.file:
        path: "{{ (vault_download_local_dir, vault_download_version) | ansible.builtin.path_join }}"
        mode: "0755"
        state: directory

    - name: Link current version directory
      ansible.builtin.file:
        src: "{{ (vault_download_local_dir, vault_download_version) | ansible.builtin.path_join }}"
        dest: "{{ vault_download_current_local_dir_link }}"
        state: link

- name: Download Vault binaries
  block:
    - name: Check if the Vault archives already downloaded
      loop: "{{ vault_download_architecture_map | ansible.builtin.dict2items }}"
      register: vault_download_files
      loop_control:
        label: "{{ vault_download_architecture.key }}"
        loop_var: vault_download_architecture
      ansible.builtin.stat:
        path: "{{ (vault_download_current_local_dir_link, vault_download_architecture.key) | ansible.builtin.path_join }}"

    - name: Download Vault archives
      when:
        - not vault_download_files.results[ansible_loop.index0].stat.exists
        - vault_download_architecture.key in common_unique_architectures
      loop: "{{ vault_download_architecture_map | ansible.builtin.dict2items }}"
      loop_control:
        label: "{{ vault_download_architecture.key }}"
        loop_var: vault_download_architecture
        extended: true
      ansible.builtin.get_url:
        url: "{{ vault_download_url }}"
        dest: "{{ (vault_download_current_local_dir_link, vault_download_architecture.key) | ansible.builtin.path_join }}"
        mode: "0644"
