---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/backups.yaml
  - resources/cert-manager.yaml
  - resources/cnpg-system.yaml
  - resources/games.yaml
  - resources/gotosocial.yaml
  - resources/longhorn-system.yaml
  - resources/ot-operators.yaml
  - resources/seaweedfs-operator.yaml
  - resources/traefik.yaml
  - resources/woodpecker.yaml
