---
- name: Get latest CoreDNS version
  when: coredns_download_version == "latest"
  block:
    - name: Fetch latest CoreDNS release on GitHub
      register: coredns_download_github_release
      community.general.github_release:
        user: "{{ coredns_download_github_user }}"
        repo: "{{ coredns_download_github_repository }}"
        token: "{{ lookup('ansible.builtin.env', 'ANSIBLE_GITHUB_API_TOKEN') }}"
        action: latest_release

    - name: Set CoreDNS version fact
      ansible.builtin.set_fact:
        coredns_download_version: "{{ coredns_download_github_release.tag | ansible.builtin.regex_replace('^v', '') }}"

- name: Link current version directory
  block:
    - name: Create version directory
      ansible.builtin.file:
        path: "{{ (coredns_download_local_dir, coredns_download_version) | ansible.builtin.path_join }}"
        mode: "0755"
        state: directory

    - name: Link current version directory
      ansible.builtin.file:
        src: "{{ (coredns_download_local_dir, coredns_download_version) | ansible.builtin.path_join }}"
        dest: "{{ coredns_download_current_local_dir_link }}"
        state: link

- name: Download CoreDNS binaries
  block:
    - name: Check if the CoreDNS archives already downloaded
      loop: "{{ coredns_download_architecture_map | ansible.builtin.dict2items }}"
      register: coredns_download_files
      loop_control:
        label: "{{ coredns_download_architecture.key }}"
        loop_var: coredns_download_architecture
      ansible.builtin.stat:
        path: "{{ (coredns_download_current_local_dir_link, coredns_download_architecture.value) | ansible.builtin.path_join }}"

    - name: Download CoreDNS archives
      when:
        - not coredns_download_files.results[ansible_loop.index0].stat.exists
        - coredns_download_architecture.key in common_unique_architectures
      loop: "{{ coredns_download_architecture_map | ansible.builtin.dict2items }}"
      loop_control:
        label: "{{ coredns_download_architecture.key }}"
        loop_var: coredns_download_architecture
        extended: true
      ansible.builtin.get_url:
        url: "{{ coredns_download_url }}"
        dest: "{{ (coredns_download_current_local_dir_link, coredns_download_architecture.key) | ansible.builtin.path_join }}"
        mode: "0644"
