---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/base/configs/cert-manager/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: traefik-controller
    - name: cert-manager-controller
