apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-server-secret
type: Opaque
stringData:
  WOODPECKER_FORGEJO_CLIENT: ENC[AES256_GCM,data:RP1ekR09jX1hy23NU9z6O3Gii8JRMvyJggtup0jOZIBoQM/u,iv:lNLsV1ZbJ8T4hbjkH0jJBhjh5CWJtnsARKWWsR/wJbc=,tag:CB4zE8mclwjbClXsllEIRQ==,type:str]
  WOODPECKER_FORGEJO_SECRET: ENC[AES256_GCM,data:6kU/hvmERSCzPnpy5uX1Sv96Pcka0V13tgvpUIBSYEO6js8gH9w27LviN7hFapcOw4/JCAlUuJg=,iv:Dct0voOh1Z4UawO80qNfVewhFXFFLcrAR0hHKjG/nck=,tag:yq0UdWanqII3d1mlMJfhWw==,type:str]
sops:
  age:
    - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MllSVEYzZloxM0pOa3Bu
        RGlMR1ZKeDc2dEx4NzA3R01jeVY4RHNrajBjCmJ1OENzay9hWjR3UzAwTVpyQUFU
        b21uTFhza2ZBNzMySjd6T2dhaDlwTjAKLS0tIHV5RUQwTDY5Yml4aXIrVFN2M29S
        OGNyR1FVUmRzYndMNC9heG16MndvTXMKcjsyaz6fGicrAxCN58/A2FmJ0pGKsQBx
        /sVAWBZGVp5oedOv2mm+nSlDRXBZp8WdX0EvG7znQbe9bhEj46GUUg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcEJZRjdRTGFrdlFyVzYr
        M1doSWpTRi9yVnd4emYvZXVLekhnZkpMeUc0Ck5QZUF4SzhnM1J6NU85TjVXYys0
        cWh1WlBJNXJYdnJpVUZsVEJwazhLeUkKLS0tIFNTME9YZFhmUWtaL0xNZFhYVEZV
        MFA3S21rbCswdURzd2lIOHdFUXNJWHMK7UioZ+xv9fSdbpALuUvdNGlu6t9qb7X3
        84qETeAph0Ny2+vXPeW26Vw5aaXq7L4fvWHKSUIillEqvQP+oPO5vg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T12:40:08Z"
  mac: ENC[AES256_GCM,data:559dg3PBNO8vjZuJ6jYylU8eAU7PY0NhQAymFSINnP+3LkzjcchxagHAPU3icMreSKL9l64tAu7pKDZraaLC1waYzaLBoDd8fe6EujT8eEniezOSG9HeTQ4KwPcgIQWYnAVtnivcPkz5ivBfIh8XOOguG9y7mJMh5E+TdsNQWAQ=,iv:Y8UaAwcExtd2yUh/bSfo3A5AG92JAdcY71LTe8WCRuw=,tag:rYmqJxYFFvqdklTWubzaVw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
