---
# Path to the K3s binary for the current architecture.
k3s_install_local_file: "{{ (k3s_download_local_dir, 'current', ansible_facts.architecture) | ansible.builtin.path_join }}"

# Target directory where K3s will be installed.
k3s_install_dir: /usr/local/bin

# Path to the K3s binary.
k3s_install_binary: "{{ (k3s_install_dir, 'k3s') | ansible.builtin.path_join }}"
