---
# Target directory where K3s will be installed.
k3s_install_dir: /usr/local/bin

# Directory where K3s configuration stored.
k3s_install_config_dir: /etc/rancher/k3s

# Path to the K3s binary.
k3s_install_binary: "{{ (k3s_install_dir, 'k3s') | ansible.builtin.path_join }}"

# Path to the K3s install script.
k3s_install_script: "{{ (k3s_install_dir, 'k3s-install.sh') | ansible.builtin.path_join }}"
