---
k3s_agent_config:
  node-ip: 10.44.4.10
  node-external-ip: 85.208.85.159

  server: https://10.44.0.10:6443
  token: "{{ k3s_agent_config_token }}"

  node-label:
    - net.kasefuchs.homelab/region=cis
    - net.kasefuchs.homelab/placement=cloud

  flannel-iface: nebula0
