---
k3s_server_config:
  disable: "{{ k3s_server_config_disable }}"

  node-ip: 10.44.4.10
  node-external-ip: 85.208.85.159
  advertise-address: 10.44.4.10

  tls-san:
    - 85.208.85.159
    - silky.vps.kasefuchs.net

  flannel-iface: nebula0
