apiVersion: v1
kind: Secret
metadata:
    name: store-secret
type: Opaque
stringData:
    redis_password: ENC[AES256_GCM,data:Ls4GzhbHD0jopZAyCHzrje0BfIiyahNoHjfcvFWJbpk=,iv:UPcV0aPx+I4nsGZfwCy8n4CDeO2O+OPEakAE2SARpCQ=,tag:gDvdW/Nw3rIKjON+WgR2mg==,type:str]
    seaweedfs_s3_config: ENC[AES256_GCM,data:8wzjS0bK1uiB3qgF9F5ZSzLyyXT+XfED+/4UKASEUtn13tNVyrmS3YL0/6i96vAKpCxg+swxO2nyAfMjCi6B+OSzxKnujoADzlHAqjycDzM4osFgK24ObiF+FcPKNioFVaxaFFysHPDatPTMvu0ld7l22NTP87rb3lxjCpQy37wOMpJRdB6CYyR+huu3a5gwT31dNjnquu4xABmJtXveh5g++jKnYwgfkw8m5Rfj4YDKt7PX9dWD0biD1XhqlgvgkhGDPtpp5t4BVSAr9rpMQMRjg/MYkSZMfLq264RRANCJQDjS2+giymPoBEU3LdKC1mWDFwizy/s6gfWint/zEPorjHpyL7bBexGoW85i380JksXd8326P0e8dRdaoT0b6Lx67GHLYA23AgZvy0+zKm2rR1LdvtUvLwhHWc9MlFld1AmMR7u9QHy0KUaqbxhp7eP8WinYpioGKH4xBSdgU7TWxzodiTvTT2C/fO4O0Dyy7tVAhJ7c/BaFTmCuG7HvGJbMcgQnYfK7vdN9fq6C+5g58EzM1uz44j0vQqVew1OufwmemjpndoaG9FIS3tjTmYPEU2OsjI9OdQ3K46oSwAecdvWOa2j36uoNqJU+1G2UcN3Q674WcLrXSeWz5Y+BZj1mg7fGct/D/nUvNOwiRIhwOcTZoLFXtOsSQeLnBaVbVbZsL9WGLhowAeKpiOOoYzQz0rCH9xrxGVQ1SeimaeUGXyjtiZL8BtDodXQdO6iCLS90,iv:Ju7bLS7rD8anGnVNSH4ziEvxBxF0syjR4jZKKjgAyR0=,tag:GvaUDeFJizJa56cKQSifTA==,type:str]
sops:
    age:
        - recipient: age1qwl6ge4gjj2mk86aj045h9z4ey8qeaca6r28uvvvtk74p7fzdpase0nevf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyd3pUbmUvQXJEUWFHNVll
            bEhZYWhPSnRRc2FyV25iNGZod2g0VXpVYjFFCk9mVUZFNnBHa0JrL0FqeW5KV3Nt
            d2RBdnFQdjZpQVdkQ2dqUHJDeHNPM1EKLS0tIG9yU2NiMzlMbWJnVjIyVWQ0TDFF
            UkxRcDN0MzhpQzh0bXI4anJZcCtraUEKhSjVaMrMG9WWPlMV5e+n3RWFylxXrPhY
            b15+dqqWjzGSDbPIs8fl3PZH4Yga6ywdGzoBCYFbeWi60V245tgUkA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1qgv4cfh20qcmhts880afhzvljxp6mv5qlcrxc6weuudew7kelsgqc0v77v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdDJHS3BwSWVLMGNVMVpz
            RGF5Nm5ST0J3ayszKy9tb2FTaUg0a2JKbHlVClZJcVRyWTlEYklrdXpRRm5YZEhI
            cURidUN6YVpzOUwvYm9yQkVVZXROazgKLS0tIDhZMkxhQUZxV3pLbnhCckQ5cFp5
            c1NCeUgrNEpWN0E3TDNYeHAyNWpIc00KpRDbgW1jWMzugUKbIPQIyGO86TQM3osu
            UqaXcNjF7VbxdtoR9x3fceBSBcMIEeZ72RBvWLPc5tEnbaDZ16DlyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-31T16:29:53Z"
    mac: ENC[AES256_GCM,data:AtJygKNIQx0YPDY97CNtqmkMuRfx1sF3oNyGa5RJaStHII+V5UPXwe8CQzPhdDem4CM3S1baeHn9uwQ+o7KXhmq+4/et5Pjdy5BQO+o6/5z5Tecp8wSTV0zFLid0sP16Rha60p2coJoI9GLG+7Hphgv2QRtxrkdQcwfRt/yDFn8=,iv:fSSiCwHFtp7RQYrELMHrRS4IZuUq7yZtG2xLwUHMvQA=,tag:/8EImntLIvTGG1g+G/XWdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
