---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/infrastructure/cert-manager/controller/kustomize
  wait: false
  prune: true
  timeout: 5m
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
